### ISSUE TITLE
When i Import styles and animation files it throws errors

### ISSUE THREAD

**Issue by sagarCS** [atomiks/tippyjs-react#224]
When i import the style and animation file like :
`
import 'tippy.js/animations/scale.css';
import 'tippy.js/dist/tippy.css';
`
and the when i run my app it throws this error:
```
ERROR in ./node_modules/tippy.js/dist/tippy.css (./node_modules/react-scripts/node_modules/css-loader/dist/cjs.js??ref--8-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./node_modules/postcss-loader/src??ref--14-0!./node_modules/tippy.js/dist/tippy.css)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
BrowserslistError: Unknown browser query `dead`
    at /home/sagar/Desktop/Latest/UI-React/node_modules/postcss-cssnext/node_modules/browserslist/index.js:164:11
    at Array.reduce (<anonymous>)
    at resolve (/home/sagar/Desktop/Latest/UI-React/node_modules/postcss-cssnext/node_modules/browserslist/index.js:132:18)
    at browserslist (/home/sagar/Desktop/Latest/UI-React/node_modules/postcss-cssnext/node_modules/browserslist/index.js:224:16)
    at Browsers.parse (/home/sagar/Desktop/Latest/UI-React/node_modules/postcss-cssnext/node_modules/autoprefixer/lib/browsers.js:61:16)
    at new Browsers (/home/sagar/Desktop/Latest/UI-React/node_modules/postcss-cssnext/node_modules/autoprefixer/lib/browsers.js:52:30)
    at loadPrefixes (/home/sagar/Desktop/Latest/UI-React/node_modules/postcss-cssnext/node_modules/autoprefixer/lib/autoprefixer.js:70:24)
    at plugin (/home/sagar/Desktop/Latest/UI-React/node_modules/postcss-cssnext/node_modules/autoprefixer/lib/autoprefixer.js:81:24)
    at LazyResult.run (/home/sagar/Desktop/Latest/UI-React/node_modules/postcss/lib/lazy-result.js:295:14)
    at LazyResult.asyncTick (/home/sagar/Desktop/Latest/UI-React/node_modules/postcss/lib/lazy-result.js:208:26)
    at LazyResult.asyncTick (/home/sagar/Desktop/Latest/UI-React/node_modules/postcss/lib/lazy-result.js:221:14)
    at LazyResult.asyncTick (/home/sagar/Desktop/Latest/UI-React/node_modules/postcss/lib/lazy-result.js:221:14)
    at LazyResult.asyncTick (/home/sagar/Desktop/Latest/UI-React/node_modules/postcss/lib/lazy-result.js:221:14)
    at LazyResult.asyncTick (/home/sagar/Desktop/Latest/UI-React/node_modules/postcss/lib/lazy-result.js:221:14)
    at LazyResult.asyncTick (/home/sagar/Desktop/Latest/UI-React/node_modules/postcss/lib/lazy-result.js:221:14)
    at LazyResult.asyncTick (/home/sagar/Desktop/Latest/UI-React/node_modules/postcss/lib/lazy-result.js:221:14)
 @ ./node_modules/tippy.js/dist/tippy.css 2:14-200 21:1-42:3 22:19-205
 @ ./src/app/common/components/Tooltip/Tooltip.tsx
 @ ./src/app/common/components/Tooltip/Tooltip.stories.tsx
 @ ./src/app/common/components sync ^\.\/(?:(?:(?!\.)(?:(?:(?!(?:|\/)\.).)*?)\/)?(?!\.)(?=.)[^\/]*?\.stories\.tsx\/?)$
 @ ./.storybook/generated-entry.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./node_modules/@storybook/addon-docs/dist/frameworks/react/config.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=true
```

can anyone help me what might be the issue?

**Comment by KubaJastrz** [comment]
```
Module build failed (from ./node_modules/postcss-loader/src/index.js):
BrowserslistError: Unknown browser query `dead`
```

It looks like you have a problem with your [browserlist configuration](https://github.com/browserslist/browserslist#config-file) and/or version mismatch.

Try to create a minimal example and it will help you to identify the root cause. It's most likely not a problem within tippy package, as we are not publishing our postcss configuration.

**Comment by sagarCS** [comment]
@KubaJastrz  that makes sense...I will look for the config set for my project.. thanks for the reply though.

**Comment by sagarCS** [comment]
@KubaJastrz  i have one more doubt if you can help me please do..
I want my tooltip content to get update when i click on button somewhat like copyclipboard where when we hover tooltip shows "click to copy" and then when user clicks the tooltip content changes to "copied".
can you just clue me in on how to approach this usecases with example or something.

**Comment by KubaJastrz** [comment]
Sure, you need to update the `content` prop:

```js
import React from 'react'
import Tippy from '@tippyjs/react'

function CopyToClipboard({children}) {
	const [hasCopied, setHasCopied] = React.useState(false)
	const onClick = () => {
		// your logic here
		setHasCopied(true)
	}
	return (
		<Tippy content={hasCopied ? 'copied' : 'click to copy'}>
			<button onClick={onClick}>copy</button>
		</Tippy>
	)
}
```

**Comment by sagarCS** [comment]
Hey @KubaJastrz ,
I tried the same thing but its not updating dynamically i mean i have to hoverout and then hover again to see the changes i want to update the content while the tooltip is opened.
here it is what i have tried:
```
const CopyClipBoard = () => {
    const [flag, setflag] = useState(false)
    return (
        <Tooltip content={flag ? "copied" : "copy"} position="right" showArrow={true}>
            <span onClick={() => {
                setflag(true)
            }}>ClipBoard</span>
        </Tooltip>
    )
}
```
does this make sense?

**Comment by sagarCS** [comment]
this is my common component ( built using tippyjs-react) that can be used to create tooltip anywhere:
```
import React, { createRef } from 'react';
import Tippy from '@tippyjs/react';
import './Tooltip.css'

interface ITooltip {
    content: string | React.ReactNode,
    position: string,
    showArrow?: boolean,
    onCreate?: (data: any) => void,
}

const Tooltip: React.FunctionComponent<ITooltip> = (props: any) => {
    const node = createRef<HTMLInputElement>()
    const { content, position, children, ...rest } = props
    const showArrow = props.showArrow || true
    return (
        <Tippy
            content={content}
            placement={position}
            arrow={showArrow}
            delay={500}
            interactive={true}
            animation='scale'
            className="contentstack"
            {...rest}
        >
            <div ref={node} style={{ display: 'inline-block' }}
            >
                {children}
            </div>
        </Tippy>
    )
}

export default Tooltip;
```
so when i call this Tooltip component for copyclipboard feature the content should update when i click on button but it does not update while tooltip is open, i have to hoverout and then hover again to see the updated content.
this is how i called my Tooltip component:
```
export const CopyClipBoard = () => {
    const [flag, setflag] = useState(false)
    return (
        <Tooltip content={flag ? "copied" : "copy"} position="right" showArrow={true}>
            <span onClick={() => {
                console.log('click copyclipboard', flag);
                setflag(true)
            }}>ClipBoard</span>
        </Tooltip>
    )
}
```
so  please provide me any suggestion or trick to make it work please.
Thanks.

**Comment by KubaJastrz** [comment]
I've definitely done dynamic content before, but I don't see anything wrong here. Can you try to wrap it with an element? Like this:
```js
<Tooltip content={<span>{flag ? "copied" : "copy"}</span>}
```

**Comment by KubaJastrz** [comment]
If that doesn't help, you can create a separate issue and close this one.

**Comment by sagarCS** [comment]
> I've definitely done dynamic content before, but I don't see anything wrong here. Can you try to wrap it with an element? Like this:
> 
> ```js
> <Tooltip content={<span>{flag ? "copied" : "copy"}</span>}
> ```

ohk thanks @KubaJastrz  for your help...i will close this issue and if it didnt work then i will create another issue thanks.
