### ISSUE TITLE
Next.js SSR: `Error: Target container is not a DOM element.`

### ISSUE THREAD

**Issue by tyteen4a03** [atomiks/tippyjs-react#229]
I'm getting this error when trying to use the Tippy component:

```
Error: Target container is not a DOM element.
    at Object.createPortal$1 [as createPortal] (/***/nextjs/node_modules/react-dom/cjs/react-dom.development.js:24946:13)
    at Tippy (/***/nextjs/node_modules/@tippyjs/react/dist/tippy-react.umd.js:312:40)
    at processChild (/***/nextjs/node_modules/react-dom/cjs/react-dom-server.node.development.js:3043:14)
    at resolve (/***/nextjs/node_modules/react-dom/cjs/react-dom-server.node.development.js:2960:5)
    at ReactDOMServerRenderer.render (/***/nextjs/node_modules/react-dom/cjs/react-dom-server.node.development.js:3435:22)
    at ReactDOMServerRenderer.read (/***/nextjs/node_modules/react-dom/cjs/react-dom-server.node.development.js:3373:29)
    at renderToString (/***/nextjs/node_modules/react-dom/cjs/react-dom-server.node.development.js:3988:27)
    at render (/***/nextjs/node_modules/next/dist/next-server/server/render.js:3:298)
    at Object.renderPage (/***/nextjs/node_modules/next/dist/next-server/server/render.js:46:1020)
    at Function.getInitialProps (webpack-internal:///./node_modules/next/dist/pages/_document.js:133:19)
    at Function.getInitialProps (webpack-internal:///./pages/_document.tsx:20:85)
    at loadGetInitialProps (/***/nextjs/node_modules/next/dist/next-server/lib/utils.js:5:101)
    at renderToHTML (/***/nextjs/node_modules/next/dist/next-server/server/render.js:46:1330)
    at async /***/nextjs/node_modules/next/dist/next-server/server/next-server.js:68:285
    at async __wrapper (/***/nextjs/node_modules/next/dist/lib/coalesced-function.js:1:330)
    at async DevServer.renderToHTMLWithComponents (/***/nextjs/node_modules/next/dist/next-server/server/next-server.js:91:254)
```

With Next.js 9.4.4, tippy-react 4.0.3 and tippy.js 6.2.3. Downgrading to tippy-react 3.1.1 and tippy.js 5.1.1 fixes the problem.

**Comment by tony** [comment]
Not sure how - but or if it's related, but 4.0.3 breaks Gatsby build (SSR) for me. 4.0.2 works

I'm guessing something to do with Poppy now doing `createdPortal` before being mounted: https://github.com/atomiks/tippyjs-react/compare/v4.0.2...v4.0.3#diff-a0cb345ea29dc4e75ff8f0803c94f035L33

**Comment by atomiks** [comment]
So the mounted call was necessary after all 😭

**Comment by atomiks** [comment]
`v4.0.4`

**Comment by tyteen4a03** [comment]
Works perfectly, thanks!
